# Generated by Django 5.1.2 on 2024-10-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='calificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
