# Generated by Django 5.1.2 on 2024-10-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_profile_delete_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='no_email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_surname',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_surname',
            field=models.CharField(default='Desconocido', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_control',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
